# SELECT ID, LENGTH
# FROM FISH_INFO
# ORDER BY LENGTH DESC, ID
# LIMIT 10

# SELECT ID, LENGTH
# FROM (SELECT ID, LENGTH, RANK() OVER (ORDER BY LENGTH DESC) AS RN FROM FISH_INFO) AS T
# WHERE RN <= 10
# ORDER BY LENGTH DESC, ID
WITH T AS (
    SELECT ID, LENGTH, RANK() OVER (ORDER BY LENGTH DESC) AS RN FROM FISH_INFO
)

SELECT ID, LENGTH
FROM T
WHERE RN <= 10
ORDER BY LENGTH DESC, ID