# WITH T AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     WHERE DURATION_TYPE = '30일 이상'
# )


# SELECT CAR_ID, CRCC.CAR_TYPE, DAILY_FEE * (100-DISCOUNT_RATE) / 100 * 30 AS FEE
# FROM CAR_RENTAL_COMPANY_CAR CRCC
# JOIN T
# ON CRCC.CAR_TYPE = T.CAR_TYPE
# WHERE (CRCC.CAR_TYPE = '세단' OR CRCC.CAR_TYPE = 'SUV')
# AND CAR_ID NOT IN (
#     SELECT CAR_ID 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE END_DATE >= '2022-11-01'
# )
# AND FEE >= 500000 AND FEE <= 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC



WITH T AS (
    SELECT CAR.CAR_ID AS CAR_ID, 
        CAR.CAR_TYPE AS CAR_TYPE, 
        ROUND(CAR.DAILY_FEE * (100 - PLAN.DISCOUNT_RATE) / 100) * 30 AS FEE
    FROM CAR_RENTAL_COMPANY_CAR CAR
    JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN PLAN
        ON CAR.CAR_TYPE = PLAN.CAR_TYPE
    WHERE (CAR.CAR_TYPE = '세단' OR CAR.CAR_TYPE = 'SUV')
        AND DURATION_TYPE = '30일 이상'
        AND NOT EXISTS (
            SELECT 1
            FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY H
            WHERE H.CAR_ID = CAR.CAR_ID
                AND START_DATE <= '2022-11-30'
                AND END_DATE >= '2022-11-01'
        )
)

SELECT *
FROM T
WHERE FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC