# # 방법 1
# WITH T AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     WHERE DURATION_TYPE = '30일 이상'
# )

# SELECT CAR_ID, CAR_TYPE, DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30 AS FEE
# FROM CAR_RENTAL_COMPANY_CAR
# JOIN T USING (CAR_TYPE)
# WHERE CAR_TYPE IN ('세단', 'SUV')
# AND CAR_ID NOT IN (
#     SELECT CAR_ID 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
# )
# AND DAILY_FEE * (100-DISCOUNT_RATE) / 100 * 30 >= 500000
# AND DAILY_FEE * (100-DISCOUNT_RATE) / 100 * 30 < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# # 방법 2
# WITH T AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     WHERE DURATION_TYPE = '30일 이상'
# )

# SELECT CAR_ID, CAR_TYPE, DAILY_FEE * (100 - DISCOUNT_RATE) / 100 * 30 AS FEE
# FROM CAR_RENTAL_COMPANY_CAR
# JOIN T USING (CAR_TYPE)
# WHERE CAR_TYPE IN ('세단', 'SUV')
# AND CAR_ID NOT IN (
#     SELECT CAR_ID 
#     FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#     WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
# )
# HAVING FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE, CAR_ID DESC

# # 방법 3
# WITH T AS (
#     SELECT *
#     FROM CAR_RENTAL_COMPANY_DISCOUNT_PLAN
#     WHERE DURATION_TYPE = '30일 이상'
# )

# SELECT CAR_ID, CAR_TYPE, FEE
# FROM (
#     SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100) * 30 AS FEE
#     FROM CAR_RENTAL_COMPANY_CAR
#     JOIN T USING (CAR_TYPE)
#     WHERE CAR_TYPE IN ('세단', 'SUV')
#     AND CAR_ID NOT IN (
#         SELECT CAR_ID 
#         FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#         WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
#     )
# ) RESULT
# WHERE FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

# # 방법 4
# WITH T AS (
#     SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100) * 30 AS FEE
#     FROM CAR_RENTAL_COMPANY_CAR CAR
#     JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)
#     WHERE CAR_TYPE IN ('세단', 'SUV')
#         AND DURATION_TYPE = '30일 이상'
#         AND CAR_ID NOT IN (
#             SELECT CAR_ID
#             FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
#             WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
#         )
# )

# SELECT *
# FROM T
# WHERE FEE >= 500000 AND FEE < 2000000
# ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC

# 방법 5
SELECT CAR_ID, CAR_TYPE, ROUND(DAILY_FEE * (100 - DISCOUNT_RATE) / 100) * 30 AS FEE
FROM CAR_RENTAL_COMPANY_CAR 
JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN USING (CAR_TYPE)
WHERE CAR_TYPE IN ('세단', 'SUV')
AND DURATION_TYPE = '30일 이상'
AND CAR_ID NOT IN (
    SELECT CAR_ID
    FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY
    WHERE START_DATE <= '2022-11-30' AND END_DATE >= '2022-11-01'
)
HAVING FEE >= 500000 AND FEE < 2000000
ORDER BY FEE DESC, CAR_TYPE ASC, CAR_ID DESC