-- 코드를 입력하세요
# SELECT F.FOOD_TYPE, REST_ID, REST_NAME, F.FAVORITES
# FROM REST_INFO RI
# JOIN (
#     SELECT FOOD_TYPE, MAX(FAVORITES) AS FAVORITES
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# ) F ON RI.FOOD_TYPE = F.FOOD_TYPE
# WHERE RI.FAVORITES = F.FAVORITES
# ORDER BY FOOD_TYPE DESC

# SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
# FROM REST_INFO
# WHERE (FOOD_TYPE, FAVORITES) IN (
#     SELECT FOOD_TYPE, MAX(FAVORITES)
#     FROM REST_INFO
#     GROUP BY FOOD_TYPE
# )
# ORDER BY FOOD_TYPE DESC

SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES
FROM (
    SELECT FOOD_TYPE, REST_ID, REST_NAME, FAVORITES, 
           RANK() OVER (PARTITION BY FOOD_TYPE ORDER BY FAVORITES DESC) AS RK
    FROM REST_INFO
) AS RKT
WHERE RK = 1
ORDER BY FOOD_TYPE DESC