# SELECT 
#     YEAR(SALES_DATE) AS YEAR, 
#     MONTH(SALES_DATE) AS MONTH, 
#     COUNT(DISTINCT USER_ID) AS PURCHASED_USERS,
#     ROUND(COUNT(DISTINCT USER_ID) / (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021), 1) AS PUCHASED_RATIO
# FROM ONLINE_SALE
# JOIN USER_INFO USING (USER_ID)
# WHERE YEAR(JOINED) = 2021
# GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
# ORDER BY YEAR, MONTH

SET @TOTAL = (SELECT COUNT(*) FROM USER_INFO WHERE YEAR(JOINED) = 2021);

SELECT 
    YEAR(SALES_DATE) AS YEAR, 
    MONTH(SALES_DATE) AS MONTH, 
    COUNT(DISTINCT USER_ID) AS PURCHASED_USERS, 
    ROUND(COUNT(DISTINCT USER_ID) / @TOTAL, 1) AS PUCHASED_RATIO
FROM USER_INFO
JOIN ONLINE_SALE USING (USER_ID)
WHERE YEAR(JOINED) = 2021
GROUP BY YEAR(SALES_DATE), MONTH(SALES_DATE)
ORDER BY YEAR, MONTH