WITH HISTORY AS (
    SELECT 
        HISTORY_ID, CAR_TYPE, DATEDIFF(END_DATE, START_DATE) + 1 AS RENT_DAYS,
        CASE 
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 90 THEN '90일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 30 THEN '30일 이상'
            WHEN DATEDIFF(END_DATE, START_DATE) + 1 >= 7 THEN '7일 이상'
        END AS DURATION_TYPE,
        DAILY_FEE
    FROM CAR_RENTAL_COMPANY_CAR
    JOIN CAR_RENTAL_COMPANY_RENTAL_HISTORY USING (CAR_ID)
    WHERE CAR_TYPE = '트럭'
)

SELECT HISTORY_ID, ROUND(DAILY_FEE * RENT_DAYS * (100 - IFNULL(DISCOUNT_RATE, 0)) / 100) AS FEE
FROM HISTORY H
LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN P
ON H.CAR_TYPE = P.CAR_TYPE AND H.DURATION_TYPE = P.DURATION_TYPE
ORDER BY FEE DESC, HISTORY_ID DESC