-- 코드를 입력하세요
## 방법 1
# SELECT F.FLAVOR
# FROM FIRST_HALF F
# JOIN JULY J ON F.FLAVOR = J.FLAVOR
# GROUP BY F.FLAVOR
# ORDER BY SUM(F.TOTAL_ORDER) + SUM(J.TOTAL_ORDER) DESC
# LIMIT 3

## 방법 2
SELECT F.FLAVOR
FROM FIRST_HALF F
JOIN (
    -- 7월 데이터를 맛별로 미리 합산
    SELECT FLAVOR, SUM(TOTAL_ORDER) AS JULY_TOTAL
    FROM JULY
    GROUP BY FLAVOR
) J ON F.FLAVOR = J.FLAVOR
ORDER BY (F.TOTAL_ORDER + J.JULY_TOTAL) DESC
LIMIT 3

## 방법 3
# SELECT FLAVOR
# FROM (
#     -- 상반기 주문량
#     SELECT FLAVOR, TOTAL_ORDER 
#     FROM FIRST_HALF
    
#     UNION ALL
    
#     -- 7월 주문량
#     SELECT FLAVOR, TOTAL_ORDER 
#     FROM JULY
# ) AS COMBINED_ORDERS
# GROUP BY FLAVOR
# ORDER BY SUM(TOTAL_ORDER) DESC
# LIMIT 3;