WITH RECURSIVE HOUR_ROWS AS (
    SELECT 0 AS NUM
    UNION ALL
    SELECT NUM + 1 FROM HOUR_ROWS
    WHERE NUM < 23
)


SELECT H.NUM AS HOUR, COUNT(DATETIME) AS COUNT
FROM HOUR_ROWS H
LEFT JOIN ANIMAL_OUTS A ON H.NUM = HOUR(A.DATETIME)
GROUP BY H.NUM
ORDER BY H.NUM
