-- 코드를 입력하세요
WITH CTE AS (
    SELECT *
    FROM USED_GOODS_BOARD B
    WHERE B.VIEWS = (SELECT MAX(`VIEWS`) FROM USED_GOODS_BOARD)
)

SELECT CONCAT('/home/grep/src/', BOARD_ID, '/', FILE_ID, FILE_NAME, FILE_EXT) AS FILE_PATH
FROM USED_GOODS_FILE 
JOIN CTE USING (BOARD_ID)
ORDER BY FILE_ID DESC