-- 코드를 입력하세요
SELECT B.CATEGORY, SUM(BS.SALES) AS TOTAL_SALES 
FROM BOOK_SALES BS
LEFT JOIN BOOK B ON BS.BOOK_ID = B.BOOK_ID
WHERE YEAR(SALES_DATE) = '2022' AND MONTH(SALES_DATE) = '01'
GROUP BY B.CATEGORY
ORDER BY B.CATEGORY