-- 코드를 입력하세요
WITH SUB AS (
    SELECT 
        CATEGORY, MAX(PRICE) OVER(PARTITION BY CATEGORY) AS MAX_PRICE
    FROM FOOD_PRODUCT
)

SELECT S.CATEGORY, MAX_PRICE, PRODUCT_NAME
FROM SUB S
JOIN FOOD_PRODUCT F ON S.CATEGORY = F.CATEGORY AND S.MAX_PRICE = F.PRICE
WHERE S.CATEGORY IN ('과자', '국', '김치', '식용유')
GROUP BY CATEGORY
ORDER BY MAX_PRICE DESC
